"""Initial Migrations

Revision ID: 0f8606fbe5ce
Revises:
Create Date: 2026-02-03 00:09:45.143511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f8606fbe5ce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), nullable=False, comment="Primary key — UUID v4"),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Short title for item",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Optional description field",
        ),
        sa.Column(
            "is_completed",
            sa.Boolean(),
            nullable=False,
            comment="Status: completed or not",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when item was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when item was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_title"), "items", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_title"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
